[2025-03-27T08:51:12.131+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-27T08:48:20+00:00 [queued]>
[2025-03-27T08:51:12.135+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-27T08:48:20+00:00 [queued]>
[2025-03-27T08:51:12.135+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-27T08:51:12.147+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_fetch_store_script> on 2025-03-27 08:48:20+00:00
[2025-03-27T08:51:12.152+0000] {standard_task_runner.py:57} INFO - Started process 83593 to run task
[2025-03-27T08:51:12.154+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_store_dag', 'run_fetch_store_script', 'manual__2025-03-27T08:48:20+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/fetch_store_dag.py', '--cfg-path', '/tmp/tmpfyykaxyu']
[2025-03-27T08:51:12.156+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask run_fetch_store_script
[2025-03-27T08:51:12.190+0000] {task_command.py:410} INFO - Running <TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-27T08:48:20+00:00 [running]> on host codespaces-d2646d
[2025-03-27T08:51:12.246+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_store_dag' AIRFLOW_CTX_TASK_ID='run_fetch_store_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T08:48:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T08:48:20+00:00'
[2025-03-27T08:51:12.248+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-27T08:51:12.248+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/home/vscode/miniconda/envs/airflow-env/bin/python /workspaces/Team-34/src/data/fetch_store.py']
[2025-03-27T08:51:12.263+0000] {subprocess.py:86} INFO - Output:
[2025-03-27T08:51:12.626+0000] {subprocess.py:93} INFO - 2025-03-27 08:51:12,625 - INFO - Datastore package initialized successfully.
[2025-03-27T08:51:19.814+0000] {subprocess.py:93} INFO - ✅ Password for 'admin' updated successfully!
[2025-03-27T08:51:19.814+0000] {subprocess.py:93} INFO - ✅ Database initialized successfully!
[2025-03-27T08:51:19.814+0000] {subprocess.py:93} INFO - Fetching data for software engineering on 2025-03-27...
[2025-03-27T08:51:19.814+0000] {subprocess.py:93} INFO - Error fetching jobs for software engineering: 403 Client Error: Forbidden for url: https://linkedin-data-api.p.rapidapi.com/get-jobs?description=software+engineering&full_time=True
[2025-03-27T08:51:19.814+0000] {subprocess.py:93} INFO - Saved courses_software_engineering_2025-03-27.csv to /workspaces/Team-34/src/csv_data/courses_software_engineering_2025-03-27.csv
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Stored courses_software_engineering_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Saved research_software_engineering_2025-03-27.csv to /workspaces/Team-34/src/csv_data/research_software_engineering_2025-03-27.csv
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Stored research_software_engineering_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Fetching data for cloud computing on 2025-03-27...
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Error fetching jobs for cloud computing: 429 Client Error: Too Many Requests for url: https://linkedin-data-api.p.rapidapi.com/get-jobs?description=cloud+computing&full_time=True
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Saved courses_cloud_computing_2025-03-27.csv to /workspaces/Team-34/src/csv_data/courses_cloud_computing_2025-03-27.csv
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Stored courses_cloud_computing_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Saved research_cloud_computing_2025-03-27.csv to /workspaces/Team-34/src/csv_data/research_cloud_computing_2025-03-27.csv
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Stored research_cloud_computing_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Fetching data for data science on 2025-03-27...
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Error fetching jobs for data science: 403 Client Error: Forbidden for url: https://linkedin-data-api.p.rapidapi.com/get-jobs?description=data+science&full_time=True
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Saved courses_data_science_2025-03-27.csv to /workspaces/Team-34/src/csv_data/courses_data_science_2025-03-27.csv
[2025-03-27T08:51:19.815+0000] {subprocess.py:93} INFO - Stored courses_data_science_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.816+0000] {subprocess.py:93} INFO - Saved research_data_science_2025-03-27.csv to /workspaces/Team-34/src/csv_data/research_data_science_2025-03-27.csv
[2025-03-27T08:51:19.816+0000] {subprocess.py:93} INFO - Stored research_data_science_2025-03-27.csv in database at /workspaces/Team-34/src/datastore/datastore.db
[2025-03-27T08:51:19.854+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-27T08:51:19.869+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=fetch_store_dag, task_id=run_fetch_store_script, execution_date=20250327T084820, start_date=20250327T085112, end_date=20250327T085119
[2025-03-27T08:51:19.889+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-27T08:51:19.898+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
