[2025-03-26T21:50:01.254+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store manual__2025-03-26T21:41:10.165521+00:00 [queued]>
[2025-03-26T21:50:01.258+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store manual__2025-03-26T21:41:10.165521+00:00 [queued]>
[2025-03-26T21:50:01.258+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-03-26T21:50:01.270+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_fetch_store> on 2025-03-26 21:41:10.165521+00:00
[2025-03-26T21:50:01.274+0000] {standard_task_runner.py:57} INFO - Started process 57074 to run task
[2025-03-26T21:50:01.277+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_store_dag', 'run_fetch_store', 'manual__2025-03-26T21:41:10.165521+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/fetch_store_dag.py', '--cfg-path', '/tmp/tmpmfc1vn8v']
[2025-03-26T21:50:01.278+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask run_fetch_store
[2025-03-26T21:50:01.305+0000] {task_command.py:410} INFO - Running <TaskInstance: fetch_store_dag.run_fetch_store manual__2025-03-26T21:41:10.165521+00:00 [running]> on host codespaces-d2646d
[2025-03-26T21:50:01.340+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_store_dag' AIRFLOW_CTX_TASK_ID='run_fetch_store' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T21:41:10.165521+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T21:41:10.165521+00:00'
[2025-03-26T21:50:01.341+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-26T21:50:01.341+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /workspaces/Team-34/src/data/fetch_store.py']
[2025-03-26T21:50:01.350+0000] {subprocess.py:86} INFO - Output:
[2025-03-26T21:50:01.700+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-26T21:50:01.701+0000] {subprocess.py:93} INFO -   File "/workspaces/Team-34/src/data/fetch_store.py", line 11, in <module>
[2025-03-26T21:50:01.701+0000] {subprocess.py:93} INFO -     import schedule
[2025-03-26T21:50:01.701+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'schedule'
[2025-03-26T21:50:01.740+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-26T21:50:01.746+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/miniconda/envs/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-26T21:50:01.749+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=fetch_store_dag, task_id=run_fetch_store, execution_date=20250326T214110, start_date=20250326T215001, end_date=20250326T215001
[2025-03-26T21:50:01.765+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task run_fetch_store (Bash command failed. The command returned a non-zero exit code 1.; 57074)
[2025-03-26T21:50:01.771+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-26T21:50:01.779+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
